### ISSUE TITLE
Bad method in plugin manager

### ISSUE THREAD

**Issue by BWorld** [zendframework/zend-filter#18]
After updating to version 2.4.9 the code breaks because in the method validatePlugin() is missing.
It seems that validate() must be renamed to validatePlugin() to satisfy the interface. 

This is at the develop branch. All unit tests are passing at master branch.

**Comment by weierophinney** [comment]
The develop branch is tested against the develop branch of
zend-servicemanager, which introduced this change. The change is correct.
Make sure you're using the develop branch of both projects.

**Comment by weierophinney** [comment]
Just as a follow-up: 2.4.9 is based on the master branch; the develop branch represents the upcoming v3, and is not compatible. Updating to 2.4.9 cannot and will not work with the develop branch.

**Comment by BWorld** [comment]
Thanks for the update. I was having minimum stability at development instead of stable, problem solved
