### ISSUE TITLE
Error: Class Zend\Filter\FilterPluginManager contains 1 abstract method...

### ISSUE THREAD

**Issue by pensiero** [zendframework/zend-filter#20]
With latest update I received this error:
```
PHP Fatal error:  Class Zend\\Filter\\FilterPluginManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend\\ServiceManager\\AbstractPluginManager::validatePlugin) in /var/www/vendor/zendframework/zend-filter/src/FilterPluginManager.php on line 0
```

Somebody know why?

**Comment by alexanderlamb** [comment]
Hitting the same error @pensiero .  Maybe Zend\ServiceManager\AbstractPluginManager changed?

**Comment by pensiero** [comment]
Resolved specifying the exact version of `zend-filter` in composer: `"zendframework/zend-filter": "2.5.*",`

**Comment by SirLouen** [comment]
Same here this thing is broken

**Comment by weierophinney** [comment]
You likely have defined composer constraints that are bringing in the dev-develop branch, which contains changes to work with zend-servicemanager v3. We're still working on updates that will allow that branch to work with either v2 or v3, but the point is: you're getting unstable code currently.

Pin your zend-filter dependency to `^2.5` to ensure you get a stable version in the 2.5 series.

**Comment by pensiero** [comment]
Thanks @weierophinney
