### ISSUE TITLE
FilterPluginManager returns NumberFormat view helper instead of filter

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zend-filter#23]
What a mistake!

This commit introduces NumberFormat view helper instead of filter into the FilterPluginManager:
https://github.com/zendframework/zend-filter/commit/a053cea29f27698c747e5709708b35c5052737a1

So view helper is returned instead of filter:
https://github.com/zendframework/zend-filter/blob/master/src/FilterPluginManager.php#L16
https://github.com/zendframework/zend-filter/blob/master/src/FilterPluginManager.php#L263

The validate method of FilterPluginManager is useless in this case, because it checks for interface and if it not pass it checks for callable, but this breaks the contract because the callable doesn't implement the FilterInterface, so the filter method cannot be called.
https://github.com/zendframework/zend-filter/blob/master/src/FilterPluginManager.php#L332

**Comment by weierophinney** [comment]
> What a mistake!

Please recognize that all of us contributing are a) human and b) fallible when you open issues. I was, and still am, tempted to delete the issue based on this, as it's disrespectful to everyone involved. If you're unsure how to word issues, try the following: "Such-and-such commit has led to the following situation ...", which makes no judgment on those who have contributed, and instead only calls out the problem.

I will create a patch and an updated release shortly.
