### ISSUE TITLE
Encrypt/Openssl Unset Difference

### ISSUE THREAD

**Issue by m1st0** [zendframework/zend-filter#35]
Zend Framework 2.4.6-2.5.3, Zend\Filter\Encrypt\Openssl.php
I believe the unset should read `unset($options['compression']);` , lines 90-93.

```
if (array_key_exists('compression', $options)) {
    $this->setCompression($options['compression']);
    unset($options['compress']);
}
```

The code above I believe results in 'Undefined index: compression' later in code.  Current workaround is to use `...->setCompression($string)` .

**Comment by samsonasik** [comment]
I've created PR #36 for it.

**Comment by m1st0** [comment]
Thank you.

**Comment by h3christophe** [comment]
Is this going to be merged into a release at some point ?

**Comment by samsonasik** [comment]
still waiting #36 to be merged
