### ISSUE TITLE
Question: Why filter? Whats about "converter"?

### ISSUE THREAD

**Issue by GodLesZ** [zendframework/zend-filter#52]
Hey folks,
this is just a naming question and belongs more or less to a definition.

In a business project I've to extend some classes to format values in a decent way.
For example a decimal number into a price with 2 decimal places, € sign and so on.

Following the PHP naming, this is _number formatting_ (see `number_format()`).
But following the zend naming, this is a _number filter_ (namespace `Zend\Filter`).

So my question is: why you (Zend tech leads/designer 🤝 ) chose `zend-filter` and not _converter_ for _formatter_?

**Comment by Ocramius** [comment]
@GodLesZ that's a very good question, but I don't think that the "transformer" and "formatter" name was very popular in 2010~2011 (when the component was first conceived).

Possibly a good candidate for rename, but 6 years in it's too late for that.
