### ISSUE TITLE
ToInt filter doesn't transform NULL to 0

### ISSUE THREAD

**Issue by tasmaniski** [zendframework/zend-filter#62]
Using zend input filter I find a bug in a case when I don't send data key to the filter,  
but still want to transform/filter data value. 
So, it should be filtered from **NULL** to **0** 

I suppose this part of the code should skip: array, object and resource
```
// is_scalar() does not consider NULL to be scalar
if (! is_scalar($value)) {
    return $value;
}
```
But unfortunately it skiped NULL value also.

Source: https://github.com/zendframework/zend-filter/blob/master/src/ToInt.php#L26

**Comment by froschdesign** [comment]
@tasmaniski 
> So, it should be filtered from NULL to 0

Sorry, this is wrong, because:

* `0` is concrete value
* `null` represents no value

So it works like described:

> `Zend\Filter\ToInt` allows you to transform a scalar value into an integer.

https://docs.zendframework.com/zend-filter/standard-filters/#toint
